#! /usr/bin/env sh

# SPDX-License-Identifier: BlueOak-1.0.0
# SPDX-FileCopyrightText: 2025 Saulius Krasuckas <saulius2_at_ar-fi_point_lt> | sskras

# - Mount a Windows Vista+ ISO image,
# - then mount the inner `INSTALL.{ESD,WIM}`
# - and access the `WinRE.wim` image stored there.

set -e

iso_file="/C/Users/Renato/Downloads/18363 .iso"
iso_full=$(cygpath -m "${iso_file}")

powershell "Get-DiskImage -ImagePath \"${iso_full}\""
