// SPDX-License-Identifier: BlueOak-1.0.0
// SPDX-FileCopyrightText: 2023-2025 Saulius Krasuckas <saulius2_at_ar-fi_point_lt> | sskras

= `iso2winre.ps1`

A tool to extract `winre.wim` from Windows installation media.

=== Occurence

I needed to change default system UI language of an installed Windows 10 from Italian to English.

Found out that it would help to have the configured `winre.wim` (Windows Recovery Environment) image in Italian replaced with an image in English.
Before repairing the Windows, that is.

For that I needed to get a different `winre.wim` file.
Found that they reside on Windows installation `*.iso` file.
But no direct way to extract `winre.wim` from there.

Hence this tool.


=== Writing

Since I am *nix guy, I start writing Bash script on Windows (using MSYS2 env) for that.
It was launching `powershell.exe` instances in row executing a specific cmd-let.
Soon I discovered that it's hard to pass the object-result on one powershell instance to another.
So I switched to PowerShell syntax early.

For testing that I also use GNU **make** and have `GNUmakefile` recipe coming along.


=== Usage

The arguments are pretty simple:

```cmd
iso2winre.ps1 INPUT_ISO [-to OUTPUT_DIR] [-interact]
```
